# Generated by Django 3.0.5 on 2020-04-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200423_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coverpic',
            field=models.ImageField(default='default1.jpg', upload_to='profile_coverpic'),
        ),
    ]
